# Generated by Django 5.2 on 2025-04-29 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(blank=True, max_length=255, null=True)),
                ('type_categorie', models.CharField(choices=[('chaussures', 'Chaussures'), ('vetements', 'Vetements'), ('sacs', 'Sacs'), ('autre', 'Autre')], default='autre', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=255)),
                ('prenom_client', models.CharField(max_length=255)),
                ('sexe', models.CharField(blank=True, choices=[('homme', 'homme'), ('femme', 'femme')], max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=250)),
                ('adresse', models.TextField()),
                ('date_cretation', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_en_stock', models.IntegerField()),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_point_de_vente', models.CharField(max_length=250)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.boutique')),
                ('gerant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerant', to='accounts.user')),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendeur', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut_transfert', models.CharField(choices=[('pending', 'En cours'), ('done', 'Terminé'), ('canceled', 'Annulé')], default='pending', max_length=50)),
                ('point_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='stock.pointdevente')),
                ('point_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='stock.pointdevente')),
            ],
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.transfert')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateField(auto_now_add=True)),
                ('prix_total_vente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.client')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('montant_HT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_TTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.vente')),
            ],
        ),
        migrations.CreateModel(
            name='VenteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire_recu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('perte', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vente_items', to='stock.vente')),
            ],
        ),
    ]
