# Generated by Django 5.2 on 2025-04-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='couleur',
            field=models.CharField(choices=[('noir', 'noir'), ('blanc', 'blanc'), ('gris', 'gris'), ('bleu', 'bleu'), ('rouge', 'rouge'), ('vert', 'vert'), ('jaune', 'jaune'), ('rose', 'rose'), ('orange', 'orange'), ('violet', 'violet'), ('marron', 'marron'), ('beige', 'beige'), ('turquoise', 'turquoise'), ('bordeaux', 'bordeaux'), ('or', 'or')], max_length=255, null=True),
        ),
    ]
