# Generated by Django 5.2 on 2025-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_alter_pointdevente_gerant_alter_pointdevente_vendeur"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="taille",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
