# Generated by Django 5.2 on 2025-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0006_article_taille"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="nom_categorie",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
