# Generated by Django 5.2 on 2025-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0007_alter_categorie_nom_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venteitem",
            name="prix_unitaire_recu",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
