# Generated by Django 5.2 on 2025-06-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_alter_venteitem_prix_unitaire_recu"),
    ]

    operations = [
        migrations.AddField(
            model_name="venteitem",
            name="benefice",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
