# Generated by Django 5.2 on 2025-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0009_venteitem_benefice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="prix_achat_unitaire",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="article",
            name="prix_vente_unitaire",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
