# Generated by Django 5.2 on 2025-06-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0010_alter_article_prix_achat_unitaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="prix_achat_unitaire",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="prix_vente_unitaire",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="vente",
            name="prix_total_vente",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="venteitem",
            name="benefice",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="venteitem",
            name="perte",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="venteitem",
            name="prix_unitaire_recu",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="venteitem",
            name="remise",
            field=models.IntegerField(),
        ),
    ]
