# Generated by Django 5.2 on 2025-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0011_alter_article_prix_achat_unitaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venteitem",
            name="total",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
