# Generated by Django 5.2 on 2025-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0012_venteitem_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venteitem",
            name="benefice",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="venteitem",
            name="perte",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="venteitem",
            name="prix_unitaire_recu",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="venteitem",
            name="remise",
            field=models.IntegerField(default=0),
        ),
    ]
