# Generated by Django 5.2 on 2025-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0013_alter_venteitem_benefice_alter_venteitem_perte_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vente",
            name="prix_total_vente",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
