# Generated by Django 5.2 on 2025-06-13 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0015_alter_vente_vendeur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferitem",
            name="article",
        ),
        migrations.RemoveField(
            model_name="transferitem",
            name="transfert",
        ),
        migrations.RemoveField(
            model_name="transfert",
            name="point_destination",
        ),
        migrations.RemoveField(
            model_name="transfert",
            name="point_source",
        ),
        migrations.AddField(
            model_name="depense",
            name="date_depense",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="depense",
            name="montant",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="Facture",
        ),
        migrations.DeleteModel(
            name="TransferItem",
        ),
        migrations.DeleteModel(
            name="Transfert",
        ),
    ]
