# Generated by Django 5.2 on 2025-06-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0016_remove_transferitem_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="date_depense",
            field=models.DateField(auto_now_add=True),
        ),
    ]
