# Generated by Django 5.2 on 2025-06-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0022_alter_categorie_type_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="point_de_vente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.pointdevente",
            ),
        ),
    ]
