# Generated by Django 5.2 on 2025-04-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_offre', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre_boutique_max', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('statut', models.CharField(choices=[('refused', 'refused'), ('accepted', 'accepted'), ('sent', 'sent'), ('expired', 'expired')], default='sent', max_length=50)),
                ('email_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'active'), ('terminated', 'terminated'), ('not_active', 'not_active')], default='not_active', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.offre')),
            ],
        ),
    ]
