# Generated by Django 5.2 on 2025-05-13 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_rename_categorie_article_categorie_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="point_de_vente",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.pointdevente",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="date_expiration",
            field=models.DateTimeField(blank=True),
        ),
    ]
