# Generated by Django 5.2 on 2025-06-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_invitation_point_de_vente_invitation_token_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
