# Generated by Django 5.2 on 2025-06-14 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_adresse_user_telephone_user_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="VendeurAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "proprietaire",
                    models.ForeignKey(
                        limit_choices_to={"is_owner": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mes_vendeurs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendeur",
                    models.OneToOneField(
                        limit_choices_to={"is_seller": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
